name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Fixes'
    labels:
      - bug
      - fix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - ci
      - deps

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No user-facing changes in this release.'

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - ci
      - deps
  default: patch

autolabeler:
  - label: 'deps'
    branch:
      - 'dependabot/**'
  - label: 'ci'
    files:
      - '.github/workflows/**'
  - label: 'feature'
    title:
      - '/feat(ure)?/i'
  - label: 'fix'
    title:
      - '/fix(e|es|ed)?/i'

template: |
  ## What's Changed
  $CHANGES
