services:
  backend:
    build: .
    container_name: budgetflow_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      DEBUG: "1"
      ALLOWED_HOSTS: "*"
      MONGO_URI: "mongodb://mongo:27017/budgetflow_db"
      CORS_ALLOW_ALL_ORIGINS: "true"
      AI_FEATURES_ENABLED: "true"
      AI_SERVICE_URL: "http://ai-service:8001"
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  ai-service:
    build: ./ai_service
    container_name: ai_service
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_PROVIDER: openai
    ports:
      - "8001:8001"
    restart: unless-stopped

volumes:
  mongodb_data:
